### ISSUE TITLE
Create PSDD4CCM Model library

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#121]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

Similarly to the DDS4CCM and AMI4CCM model libraries that are provided by CX, we would like a PSDD4CCM model library created and packaged with CX. AXCIOMA now supports PSDD4CCM (built off ZeroMQ). I am provided the idl file for the connector. Additionally, I am provided a modified version of our BasicPubSub example. In this example, nothing in the model has been changed, however, the IDL and CDP file have been modified to utilize this connector and this project has been verified to run
[BasicPubSub_PSDDv3.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/4552930/BasicPubSub_PSDDv3.zip)
[ccm_psdd.idl.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/4552933/ccm_psdd.idl.txt)

**Comment by J17359** [comment]
This enhancement would be prioritized AFTER the Model Merging Improvements (Ernesto is working on with Papyrus Compare) and helping us with sharing models across projects/repositories (we will get back to you on testing the git-submodules with the sub-models that Paul/Young-Soo described).

**Comment by ysroh** [comment]
[CCM_PSDD.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/4880558/CCM_PSDD.zip)

An initial version of the PSDD library.
Can you please check to see if I am doing this right? I will be updating BasicPubSub model with this library to test if this is good.

**Comment by j26151** [comment]
This looks good for the most part. A few comments:

1. The image is missing from the ports. We can talk about what we want for an image at our meeting
2. Configuration properties are missing. If you look at my BasicPubSub_PSDD.cdp file, you will see that there are configuration properties for both the subscriber and publisher that contain values for:  topic_name, endpoints, and whether or not to publish/subscribe
3. The data space for the model library is called "DDS_Event" this should be "PSDD_Event"
4. If the ports are connected to the event object with a ConnectorStatusListener connection, CSL connections are created which is not a thing for PSDD. This brings us back to a improvement that we would like in CX which is to no longer have 2 different connections (connector and connectorstatuslistener) and instead just have a single "connection" where if the connection is between two DDS based ports, a CSL checkbox is available (or if it has to be always available, it does nothing for other connectors like PSDD or Client-server)

**Comment by J17359** [comment]
In list item 4. above, Eric is referencing this GitHub issue (https://github.com/ZeligsoftDev/CX4CBDDS/issues/74).

**Comment by j26151** [comment]
For the image, please use the same images that are used for DDS write and DDS listen ports

**Comment by ysroh** [comment]
Can you please check the latest model library? I tested with modified BasicPubSub using regular connection.

**Comment by ysroh** [comment]
[BasicPubSub_PSDD.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/4897972/BasicPubSub_PSDD.zip)

**Comment by j26151** [comment]
Where do I find the latest model library? Earlier in the week you attached it, but I only see the modified BasicPubSub example.

**Comment by ysroh** [comment]
The model library is already merged to the Papyrus branch so it will be available if you update your CX tool to the latest.

**Comment by ysroh** [comment]
You can select import -> import registered package to import the library.

**Comment by ysroh** [comment]
[PSDD_LIBRARY.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/4898809/PSDD_LIBRARY.zip)

Also uploading the library here.

**Comment by j26151** [comment]
@ysroh  I don't see it in Papyrus. I think the issues is that the psdd model library is not in the pom.xml file: https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/bundles/pom.xml  
If there is anyways we could get this in today, that would be great.

**Comment by ysroh** [comment]
Yes. I think you are right. I will include that in the pom file.

**Comment by ysroh** [comment]
It should be available now.

**Comment by j26151** [comment]
I am not able to see it. It is not showing up as an installed plugin, either. Can you verify that installing CX on your system shows that option?

**Comment by ysroh** [comment]
I tested the installed version but the model library on my workspace had dynamic pathmap so it fooled me. I will commit the fix soon.

**Comment by j26151** [comment]
I am able to pull it in now, thank you.  I am currently seeing two issues.

1. When I create a templated instantiation of the PSDD connector and generate IDL. The IDL file for the connector is missing the include for "ccm_psdd.idl". For DDS connectors, this include is generated automatically, we need the same for PSDD.
2. The taginfo.xml file seem incorrect for the subscriber side. Specifically the "get" and "set" attribute tags for the attributes within the "data_listener" interface within the Subscribe port. The attributes are generated, but for the class "testDataSub_exec_i" when it should be for the class "testDataSub_data_listener_exec_i"

**Comment by ysroh** [comment]
> I am able to pull it in now, thank you. I am currently seeing two issues.
> 
> 1. When I create a templated instantiation of the PSDD connector and generate IDL. The IDL file for the connector is missing the include for "ccm_psdd.idl". For DDS connectors, this include is generated automatically, we need the same for PSDD.

ys] I added generate option to include "ccm_psdd.idl"

> 2. The taginfo.xml file seem incorrect for the subscriber side. Specifically the "get" and "set" attribute tags for the attributes within the "data_listener" interface within the Subscribe port. The attributes are generated, but for the class "testDataSub_exec_i" when it should be for the class "testDataSub_data_listener_exec_i"

ys] Can you provide me with the expected result? If the BasicPubSub model with DCPS connector generates correct taginfo then I assume that I have to insert a new logic to calculate the class name.

> 3. In generation of the CDP, you place all configurable attributes for the publisher and subscriber on both, the publisher and subscriber. i.e. the publisher has attributes for publish, subscriber, publisher endpoints, and subscriber endpoints. The subscriber has all 4 as well. This causes issues with both sides trying to bind to the publisher's endpoint. In the CDP file that I provided you, only the subscriber relevant attributes go to the subscriber port, and same with the publisher.

ys] Currently, if you don't set the value then the config property is not generated. However, if you do not want to see the entry from the properties view, then not sure how to do this as attributes for both ports are coming from the PSDD_Event dataspace.


It would be helpful if you can provide me with the BasicPubSub model if it is different than what I provided and the expected generated codetag info file.

Thanks.

**Comment by j26151** [comment]
I have attached a zip file with what you are requesting. 

> ys] Can you provide me with the expected result? If the BasicPubSub model with DCPS connector generates correct taginfo then I assume that I have to insert a new logic to calculate the class name.

I believe the issue is that the taginfo is showing the port name only, and not considering the class within the port that actually contains the attributes. I have attached both what I believe to be the incorrect and currently generated version ".taginfo.xml.incorrect" as well as the hand modified version that I believe to be correct ".taginfo.xml.correct"

> ys] Currently, if you don't set the value then the config property is not generated. However, if you do not want to see the entry from the properties view, then not sure how to do this as attributes for both ports are coming from the PSDD_Event dataspace.

I have attached the correct version of the CDP file (sorry to leave out the actual generated version, but you could generate it with the provided model if you need). The issue here is that the dataspace asks for all attributes, publish, subscribe, publishing endpoints, subscribing endpoints, and those all trickle down to all of the ports connected. However, the subscribing ports **cannot** be able to have the values for publish and publishing endpoints and visa-versa for the publishing ports. This causes issues. So, if the solution is "When using PSDD, configure each port separately  and do not configure the dataspace in the deployment plan" then so be it, but I want to verify that this is how we **have** to use it.
[PSDD_issues.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/4907623/PSDD_issues.zip)

**Comment by ysroh** [comment]
Thanks. I can start working on this but will take at least a few days to fix it.

**Comment by ysroh** [comment]
The second issue is fixed and I modified the model to generate the correct cdp file. Let me know if this is good. 
[PSDDPubSub_ys.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/4909955/PSDDPubSub_ys.zip)

**Comment by j26151** [comment]
I have brought in the new update, and I still see the second issue. I have verified the first issue ("ccm_psdd.idl" is fixed) and that modifying the deployment plan with the work around fixes the third issue. However, I have not seen the taginfo.xml file being generated correctly. In the subscriber's taginfo.xml, the class name for the methods "listen_mode" and "max_data" are still incorrect per the example taginfo.xml files I sent you previously.

**Comment by ysroh** [comment]
Can you try to remove the port type of the subscriber port and add back the PSDD_Subscribe port? Or you could also try to repair workerfunctions. The class name is derived from the workerfunction and it must have been already created when the port type is set.

**Comment by j26151** [comment]
That looks like it did it. I just needed to repair the worker functions. Thank you. I am okay will closing this ticket. If we see any subsequent issues, we will open up bug reports in the future.

**Comment by ysroh** [comment]
Sounds good. Thanks
