### ISSUE TITLE
Attempt to convert .emx to .uml fails with no warning or error when .uml already exists

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#276]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
A bug exists where if the export tool would overwrite any .uml file, it will not export anything and not display any message to the user that an error occurred.

To reproduce, attempt to export BasicPubSub.emx as .uml with an already created BasicPubSub.uml file existing in the same location. It would be nice if the export tool would ask whether or not to overwrite the existing .uml file or at least warn that no export will happen because it exists.

**Comment by ysroh** [comment]
Fix committed to the master branch.

**Comment by j26151** [comment]
@ysroh This fixes the easiest scenario, however it still fails with referenced models. 

If ClientServer.emx referenced BasicPubSub.emx, then using the Export Tools on ClientServer.emx causes both ClientServer.uml and BasicPubSub.uml to be created. This is good. However, if BasicPubSub.uml already exists, the Export Tools on ClientServer.emx will fail silently, because even though ClientServer.uml doesn't exist (which your PR handles now if it did), BasicPubSub.uml does, which fails the entire operation.

**Comment by ysroh** [comment]
@j26151 I see. It is a bit more complicated than I thought. I will work on this and let you know.

**Comment by ysroh** [comment]
Fix merged to master branch. Thanks

**Comment by j26151** [comment]
This fixed it for us, thank you. Feel free to close this issue.

**Comment by ysroh** [comment]
Thanks
