### ISSUE TITLE
Element Selection Dialog Browse option not working

### ISSUE THREAD

**Issue by J75880** [ZeligsoftDev/CX4CBDDS#98]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
When attempting to give a type to an element within a model, the Element Selection Dialog box's Browse option is not working and only displays a blank page. It should show a Project Explorer that allows the user to search through the different projects in the workspace.

**Comment by J75880** [comment]
It looks like this is still an issue. I would expect the Browse tab to show a project explorer view that would allow the user to look through each project in the workspace to find the desired element type like in RSA.

**Comment by ysroh** [comment]
Can you let me know the exact steps to reproduce this issue? or the reproducer model would be good too. I can browse the elements on my environment so I think there is some specific case where this is an issue.

**Comment by J75880** [comment]
So, if you open a project's model, and go to any of it's components, then add a port interface. Next, go to set the type in the CX view and this should open a dialog box with two tabs: Search and Browse. It defaults to the Search tab, but when you switch to the Browse tab, all I'm seeing is a white screen when I'd expect to see a model explorer that would show all the models in the workspace. This has happened for every model I've tried this on. To reproduce, I used an unmodified BasicPubSub Example, added a port interface to its model, and tried to set its type from the Browse tab and got a white screen.

**Comment by ysroh** [comment]
Hi Jonathan,

I am also using the BasicPubSub model and I see the browse tab working fine.

Can you please attach the model to the issue? Or send me the model via  email so I can try myself?

 

Thanks.

 

Regards,

 

Young-Soo Roh

Sr. Software Developer

Zeligsoft (2009) Ltd.

**Comment by J75880** [comment]
[Uploading BasicPubSub.zip…]()

Here's an example project where I'm seeing this issue.

**Comment by ysroh** [comment]
Is the sample model uploaded? It says "Uploading ... " and I can't download it.

**Comment by J75880** [comment]
[BasicPubSub.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/4410436/BasicPubSub.zip)

I think it uploaded this time. Sorry about that.

**Comment by ysroh** [comment]
I got it but it works on my env. I suspect that there is an another model that causes the problem in your workspace. Can you please attach any error log messages related to this action? You can open Error log from "Windows->View->Error Log" menu.

**Comment by J75880** [comment]
[errorLog (2).txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/4414580/errorLog.2.txt)

Here's the error log. It's throwing an unhandled loop exception. I have a project in my workspace with several subdirectories and each of these subdirectories contains a ModelFiles directory. For example, if you open project A you see the subdirectories B, C, and D. I think that since there is not ModelFiles directory within this project A this causes the issue.

**Comment by ysroh** [comment]
I've just committed the fix.

**Comment by ysroh** [comment]
Can you verify if this is resolved?

**Comment by J75880** [comment]
It does not look like this resolved the issue. The issue still occurs and the same error log message seems to appear. I can attach that as well if you'd like.

**Comment by ysroh** [comment]
Thanks. Can you please attach the log again? So you have the latest code?

**Comment by J75880** [comment]
[ERROR_LOG.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/4445550/ERROR_LOG.txt)

Here's my error log. And yes I working off of the latest code.

**Comment by J75880** [comment]
[NEW_ERROR_LOG.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/4469298/NEW_ERROR_LOG.txt)

Still appears to not be working. There definitely appears to be a model in the workspace causing this issue, but I don't believe that it should prevent other models from being able to utilize the Browse tab (like BasicPubSub for example).

**Comment by ysroh** [comment]
Thanks for the error log. This should be fixed now.

**Comment by J75880** [comment]
Tested and confirmed that the issue is now fixed.
